#!/bin/bash
CONFIG_DIR="$HOME/.config/cloudflare-tools"

echo "GPG keys are not deleted"
read -p "Are you sure? (y/n): " answer

if [[ "$answer" =~ ^[Yy]$ ]]; then
    echo "Removing..."
else
    echo "Aborting..."
    exit
fi


rm -rv $CONFIG_DIR

